version: '3'
services:
  project:
    container_name: app_cont
    build: .
    ports:
      - '5000:5000'
    networks:
      - backend

  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB = admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ./db/:/var/lib/postgresql/data


networks:
  backend:
    driver: bridge



